global:
  russian: По-русски
  english: English
  headline: Агентство digital-маркетинга
  customerservice: Служба поддержки клиентов
  contract: Договор
  offer: Коммерческое предложение

footer:
  descriptor: ICOACH. Продюсерский центр для тренеров, коучей и&nbsp;экспертов.
  lead: Упакуем продукт и&nbsp;создадим стабильный и&nbsp;управляемый поток целевых клиентов, пока вы&nbsp;будете заниматься другими делами
  copyright: Все права защищены

pages:
  main: Главная
  reviews: Отзывы
  shop: Каталог продуктов
  pay: Оплата с помощью Visa/MasterCard
  lead: Ручное добавление лида
  privacy: Политика конфиденциальности
